# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Info
    directives_ordering: info
    always_declare_return_types: info

    # Warning
    unsafe_html: warning
    no_logic_in_create_state: warning
    empty_catches: warning
    close_sinks: warning

    # Error
    always_use_package_imports: error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    valid_regexps: error
    always_require_non_null_named_parameters: error

linter:
  rules:
    # Enabling rules
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    require_trailing_commas: true

    # Disable rules
    sort_pub_dependencies: false
    prefer_relative_imports: false
    curly_braces_in_flow_control_structures: false
