name: flutter_coffee_shop
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.3.8
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  meta: ^1.10.0
  cached_network_image: ^3.3.1
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: ^2.2.0
  sqflite: ^2.3.3+1
  path_provider: ^2.0.0
  path: ^1.9.0
<<<<<<< HEAD
=======
  location: ^6.0.1
  yandex_mapkit: ^4.0.2
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
>>>>>>> feature/lab-4_map_screen
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  drift_dev: ^2.18.0
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/
    - fonts/

  fonts:
    - family: Roboto700
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: Roboto600
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
    - family: Roboto500
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
    - family: Roboto400
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400

