// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiSEhmOu1R2qhEg2waCCiKB3dTyKc_6Mc',
    appId: '1:980843434832:web:e43b6c48a2dad287bf9255',
    messagingSenderId: '980843434832',
    projectId: 'flutter-coffee-shop-3954f',
    authDomain: 'flutter-coffee-shop-3954f.firebaseapp.com',
    storageBucket: 'flutter-coffee-shop-3954f.appspot.com',
    measurementId: 'G-W14FYP0Y02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_QYUBM22ES03GVU9ENvfN3_JLYnwXx50',
    appId: '1:980843434832:android:b51c88dcdb0904ebbf9255',
    messagingSenderId: '980843434832',
    projectId: 'flutter-coffee-shop-3954f',
    storageBucket: 'flutter-coffee-shop-3954f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTZ0EqI3d_5diyWYdnAIqMIkk-GgYZdxs',
    appId: '1:980843434832:ios:ec104fc2e83a1a56bf9255',
    messagingSenderId: '980843434832',
    projectId: 'flutter-coffee-shop-3954f',
    storageBucket: 'flutter-coffee-shop-3954f.appspot.com',
    iosBundleId: 'com.example.flutterCourse',
  );
}
